add aks-aso chart
mboersma/cluster-api-charts pull request #3
Opened 2024-05-03 21:10 UTC by nojnhuh

2024-05-03 21:21 UTC, dtzar requested changes
If we're going with the flat directory (no sub azure folder) how you have it, then I think we should name this chart azure-aks-aso.

2024-05-03 21:31 UTC, dtzar commented
I also recommend putting in a basic readme at the root so people know the difference between this chart and the other AKS chart.

2024-05-07 17:43 UTC, mboersma commented
Apprently `helm-lint` is [overly strict](https://github.com/helm/chart-testing/issues/192) with the `maintainers:` field in Chart.yaml. It can't be empty and `name` must be a valid GitHub handle. I was investigating this in #7.

That may be fine for us, or we could consider disabling that check.

2024-05-07 17:57 UTC, dtzar commented
No, I think we should adhere to the lint with maintainers.  It's easy to add that field in there.  The linter doesn't make you maintain the chart if you put your name in there 😅

2024-05-10 19:24 UTC, mboersma commented on charts/azure-aks-aso/templates/cluster.yaml
> +  name: {{ include "capz.clusterName" .  | quote }}
```suggestion
  name: {{ include "capz.clusterName" . | quote }}
```

2024-05-10 19:24 UTC, mboersma commented on charts/azure-aks-aso/templates/cluster.yaml
> +    name: {{ include "capz.clusterName" .  | quote }}
```suggestion
    name: {{ include "capz.clusterName" . | quote }}
```

2024-05-10 19:24 UTC, mboersma commented on charts/azure-aks-aso/templates/cluster.yaml
> +    name: {{ include "capz.clusterName" .  | quote }}
```suggestion
    name: {{ include "capz.clusterName" . | quote }}
```

2024-05-10 19:24 UTC, mboersma commented on charts/azure-aks-aso/templates/cluster.yaml
> +  name: {{ include "capz.clusterName" .  | quote }}
```suggestion
  name: {{ include "capz.clusterName" . | quote }}
```

2024-05-10 19:24 UTC, mboersma commented on charts/azure-aks-aso/templates/cluster.yaml
> +  name: {{ include "capz.clusterName" .  | quote }}
```suggestion
  name: {{ include "capz.clusterName" . | quote }}
```

2024-05-10 19:24 UTC, mboersma commented on charts/azure-aks-aso/values.yaml
> +kubernetesVersion: v1.28.3
```suggestion
kubernetesVersion: v1.28.9
```

2024-05-14 14:58 UTC, nojnhuh commented
Sorry, I'm not sure I'll be able to get back to this soon. @dtzar @mboersma Could you please make the follow-up changes?

2024-05-14 15:14 UTC, mboersma commented
/assign

2024-05-14 16:08 UTC, dtzar approved these changes

2024-05-14 16:32 UTC, mboersma commented
Oops, sorry @dtzar I added a README.md after you approved this. PTAL whenever you have a chance.

2024-05-14 16:39 UTC, dtzar approved these changes

2024-05-14 16:39 UTC, merged